Added dynamic X keyboard event monitoring to qvm_start_daemon.py
QubesOS/qubes-core-admin-client pull request #146
Opened 2020-07-02 17:24 UTC by marmarta

Update keyboard_layout property whenever guivm's layout changes, instead of
only at the start.

requires QubesOS/qubes-core-admin#350

references QubesOS/qubes-issues#1396
references QubesOS/qubes-issues#4294

2020-07-02 18:55 UTC, marmarta commented
@marmarek, I'm not sure where exactly should we test this

2020-07-12 23:19 UTC, marmarek requested changes

2020-07-12 23:19 UTC, marmarek commented on qubesadmin/tools/qvm_start_daemon.py
> +            self.current_vm.keyboard_layout = current_property
```suggestion
            self.current_vm.keyboard_layout = new_property
```

2020-07-12 23:19 UTC, marmarek commented on qubesadmin/tools/qvm_start_daemon.py
> +                                 is_checked=is_checked)
I'm not really sure about usefulness of this, but it may be better to move `XkbExtension` and related classes to a separate file.

2020-07-12 23:19 UTC, marmarek commented on qubesadmin/tools/qvm_start_daemon.py
> +        self.qubes = qubesadmin.Qubes()
There is a `Qubes()` instance already in this process, better use that one.

2020-07-15 11:41 UTC, marmarek requested changes
Erroneous vim swap files added. Otherwise it is fine now.

2020-07-15 12:04 UTC, marmarta commented
> Erroneous vim swap files added. Otherwise it is fine now.

fixed... that'll teach me to avoid git add . like the plague...

2020-07-15 13:46 UTC, merged