Fix misparsing of literal `--` by `qvm-run`
QubesOS/qubes-core-admin-client pull request #214
Opened 2022-05-21 18:23 UTC by DemiMarie

`qvm-run` misparsed a COMMAND argument that is literally `--`, causing
it to crash with an uncaught exception.  Additionally, the first `--` in
the arguments is swallowed, leading to option injection.

2022-05-26 02:43 UTC, marmarek requested changes

2022-05-26 02:43 UTC, marmarek commented on qubesadmin/tests/tools/qvm_run.py
> +            ['--no-gui', '--dispvm', 'test-vm', 'command', '--', 'arg'],
Written this way, `test-vm` should be really interpreted as a command (and no explicit base VM for DispVM - use default). If you want explicit base VM, then use `--dispvm=test-vm`. I'm not sure if argparse can make this distinction...

2022-05-26 03:14 UTC, marmarek commented
PipelineRetry

2022-05-26 15:20 UTC, DemiMarie commented on qubesadmin/tests/tools/qvm_run.py
> +            ['--no-gui', '--dispvm', 'test-vm', 'command', '--', 'arg'],
Ugh, you are correct.  I should report these bugs to Python upstream, but honestly I think argparse doesn’t provide sufficient low-level control for what we need.  I would also like to raise a deprecation warning if no `--` is used, and I don’t think argparse supports that either.  I suggest switching to getopt or just parsing options manually.

For now, I changed these tests to not trigger the bug, and added a new test marked as “expected failure”.

2022-05-30 15:23 UTC, DemiMarie commented on qubesadmin/tools/qvm_run.py
> +            raise AssertionError('args.cmd misparsed somehow?  (this is a bug)')
Of course these lines are not covered by tests.  They are supposed to be unreachable, after all.

Is there a way to indicate this to the coverage code?

2022-07-13 15:50 UTC, marmarek approved these changes

2022-07-13 21:26 UTC, merged