Add a mock Qubes object with improved contents
QubesOS/qubes-core-admin-client pull request #267
Opened 2023-12-11 12:28 UTC by marmarta

Also several convenience methods and pre-populated Qubes setups.

2024-01-02 16:02 UTC, marmarta commented
PipelineRetryFailed

2024-01-03 03:42 UTC, marmarek requested changes

2024-01-03 03:42 UTC, marmarek commented on qubesadmin/tests/mock_app.py
> +            result += "rw=True\n"
That's the other way around: here rw=False, and otherwise rw=True.

2024-01-03 23:13 UTC, marmarek approved these changes

2024-01-04 14:20 UTC, merged