Add symlinks to qvm-device
QubesOS/qubes-core-admin-client pull request #269
Opened 2023-12-22 23:53 UTC by DemiMarie

These were only in dom0, which is inconsistent.

Fixes: QubesOS/qubes-issues#8786

2024-01-03 02:11 UTC, marmarek commented
For this to work, there needs to be a similar PR removing qvm-device symlinks from core-admin, otherwise packages will conflict.

2024-01-03 19:42 UTC, DemiMarie commented
What about package upgrades?

2024-01-03 21:13 UTC, marmarek commented
It will require appropriate dependencies for clean upgrades. I'll add them after merging.

2025-01-06 14:45 UTC, marmarek requested changes
Man page needs symlinks too.

2025-01-06 14:46 UTC, marmarek commented
> It will require appropriate dependencies for clean upgrades. I'll add them after merging.

Interestingly, rpm is happy with two packages owning the same file - I guess it works because the file is exactly the same.

2025-01-08 03:57 UTC, marmarek approved these changes

2025-01-08 04:25 UTC, merged