Add --yes option and confirm prompt.
QubesOS/qubes-core-admin-client pull request #44
Opened 2017-12-29 22:19 UTC by tasket

Have `qvm-remove` prompt user unless `--yes` option specified.

2017-12-30 13:29 UTC, marmarek requested changes

2017-12-30 13:29 UTC, marmarek commented on qubesadmin/tools/qvm_remove.py
> +parser.add_argument("--yes", action="store_true", dest="no_confirm",
Lets name it as in other tools: --force, -f

2017-12-30 13:29 UTC, marmarek commented on qubesadmin/tools/qvm_remove.py
> +        print("This will completely remove the selected VM(s)...")
I'd repeat VMs list here.

2018-01-01 19:19 UTC, marmarek commented on qubesadmin/tools/qvm_remove.py
> +parser.add_argument("--yes", action="store_true", dest="no_confirm",
Or at least add short version: `-y`.

2018-01-02 07:14 UTC, tasket commented
Just thought I'd mention qvm_template_postprocess uses "--really" and qvm_backup uses "--yes"
:)

2018-01-03 10:14 UTC, tasket commented
Avoid cloning installed_by_rpm: Copying `True` status doesn't make sense here, so new VM gets default.

2018-01-05 15:15 UTC, marmarek commented
I've pushed this from my account for travis check. Results:
 - missing --force, -f in documentation (`doc/manpages/qvm_remove.rst`). 
 - unit tests needs to be adjusted - currently wait for interactive confirmation

https://travis-ci.org/marmarek/qubes-core-admin-client/builds/325474606

2018-01-05 23:15 UTC, tasket commented
OK, added to manpage.

2018-01-05 23:36 UTC, tasket commented
The testing framework is unfamiliar to me. I tried looking at test modules for commands I know accept input, but I don't have time to delve into it now.

2018-01-06 03:42 UTC, marmarek commented
I've pushed tests update. One remaining thing is pylint complaining about:
```
************* Module qubesadmin.tools.qvm_remove
R: 45, 4: Unnecessary "else" after "return" (no-else-return)
```

2018-01-06 04:16 UTC, tasket commented
Ah, OK.

Also, review request (add vm listing) is also satisfied, I think.

2018-01-06 05:14 UTC, tasket commented
I did a `pull` to get your commit, and then a `push`. What do you suggest?

2018-01-06 12:53 UTC, marmarek commented
> I did a pull to get your commit, and then a push. What do you suggest?

If you want to avoid merge commit, you could do that either in opposite order, or use `pull --rebase`.

2018-01-06 13:53 UTC, marmarek approved these changes

2018-01-06 14:05 UTC, merged